### ISSUE TITLE
Using java.lang.Integer as Field Type

### ISSUE THREAD

**Issue by pete-proton** [DanielaSfregola/random-data-generator#102]
Hello,

Once I convert this
```
case class SomeClass (
 someField: Int
)
```
to
```
case class SomeClass (
 someField: java.lang.Integer
)
```
I start getting an error on
```
    for {
      ad <- Gen.oneOf(random[SomeClass](testsNum))
    } yield {
      ad
        .toJson
    }
```
which is below. 
```
Error:(17, 49) not enough arguments for method random: (implicit evidence$3: reflect.runtime.universe.WeakTypeTag[SomeClass], implicit evidence$4: org.scalacheck.Arbitrary[SomeClass])Seq[SomeClass].
Unspecified value parameter evidence$4.
      ad <- Gen.oneOf(random[SomeClass](testsNum))
Error:(17, 49) could not find implicit value for evidence parameter of type org.scalacheck.Arbitrary[SomeClass]
      ad <- Gen.oneOf(random[SomeClass](testsNum))
```

Could you help understanding how to tackle that? Sorry for the noise.

**Comment by pete-proton** [comment]
Seems importing `jIntGenArb` into the scope resolves the issue
```
  lazy val jIntGen = Arbitrary.arbitrary[Int].map(_.asInstanceOf[Integer])
  implicit val jIntGenArb = Arbitrary(jIntGen)
```

**Comment by pete-proton** [comment]
Seems adding `jIntGenArb` into the scope resolves the issue
```
case class SomeClass (
 someField: java.lang.Integer
)
  val jIntGen = Arbitrary.arbitrary[Int].map(_.asInstanceOf[Integer])
  implicit val jIntGenArb = Arbitrary(jIntGen)

    for {
      ad <- Gen.oneOf(random[SomeClass](testsNum))
    } yield {
      ad
        .toJson
    }
```

**Comment by pete-proton** [comment]
Maybe worth adding java wrapper types as implicit arbitraries by default?

**Comment by pete-proton** [comment]
I mean this does not seem to work
```
case class SomeClass (
 someField: java.lang.Integer
)
case class WIthSomeClass (
 someField: SomeClass
)

  val jIntGen = Arbitrary.arbitrary[Int].map(_.asInstanceOf[Integer])
  implicit val jIntGenArb = Arbitrary(jIntGen)

    for {
      ad <- Gen.oneOf(random[WIthSomeClass](testsNum))
    } yield {
      ad
        .toJson
    }
```
so, I have to define Arbitrary[WIthSomeClass] as well in this case. and the deeper this class in the hierarchy, the more trouble it creates.

**Comment by DanielaSfregola** [comment]
Hi @pete-proton, thanks for raising this issue.

Yes, I think you are correct: the issue is that the compiler cannot find an arbitrary instance for `java.lang.Integer`. I would suggest you raise an issue in the `scalacheck` repo (we simply use the defaults defined in scalacheck)

Although, I would argue that you shouldn't use `java.lang.Integer`, rather than `Int`. Why is this the case for you?

Regards,
Daniela

**Comment by pete-proton** [comment]
thank you, @DanielaSfregola, for prompt response. 

> I would suggest you raise an issue in the scalacheck repo (we simply use the defaults defined in scalacheck)

ok, will do. thank you for suggestion.

> Although, I would argue that you shouldn't use java.lang.Integer, rather than Int. Why is this the case for you?

good point. I am migrating from json spray to jackson & need Integer because it is nullable & that way through reflection some validation can be done on the bean, whereas for Int it is a primitive & there is no way to post check whether value was null or absent for a field. so, in a nutshell I need it to be nullable, if that makes sense.

**Comment by DanielaSfregola** [comment]
Oh I see! You could also be solving your issue by providing an instance for `Arbitrary[java.lang.Integer]`.

What happens if you add the following in the scope where you are invoking `random[SomeClass]`?

```
implicit val integerArbitrary: Arbitrary[java.lang.Integer] = implicitly[Arbitrary[Int]].map(_.asInstanceOf[java.lang.Integer])
```

Cheers,
Daniela

**Comment by pete-proton** [comment]
> Oh I see! You could also be solving your issue by providing an instance for `Arbitrary[java.lang.Integer]`.
> 
> What happens if you add the following in the scope where you are invoking `random[SomeClass]`?
> 
> ```
> implicit val integerArbitrary: Arbitrary[java.lang.Integer] = implicitly[Arbitrary[Int]].map(_.asInstanceOf[java.lang.Integer])
> ```
> 
> Cheers,
> Daniela

@DanielaSfregola that does solve the problem for `SomeClass`, but for nested classes like described [here](https://github.com/DanielaSfregola/random-data-generator/issues/102#issuecomment-579714229) I need to do some mumbo jumbo, i.e. providing arbitrary for `WIthSomeClass`, which has to be built manually, since adding `implicit val integerArbitrary` no longer works. Hope that makes sense.

**Comment by DanielaSfregola** [comment]
Weird, if you are using case classes the type class derivation should have no problem in automatically generating an Arbitrary for each case class, even if nested.

I'd do some investigation and try to replicate the issue! :)

**Comment by pete-proton** [comment]
yeah, looks a bit weird to me. thank you, @DanielaSfregola, very much

**Comment by pete-proton** [comment]
I found a way to stick with Ints and it made the life way easier. The workaround is below
```scala
import com.fasterxml.jackson.databind.{ BeanProperty, DeserializationContext, JsonDeserializer }
import com.fasterxml.jackson.databind.deser.ContextualDeserializer
import com.fasterxml.jackson.databind.deser.std.StdDeserializer
import javax.annotation.Nonnull
import scala.reflect.ClassTag

abstract class NonNullDeserializer[T](
  nullable: Boolean = true,
  fieldName: String = null)(implicit classTag: ClassTag[T])
  extends StdDeserializer[T](classTag.runtimeClass)
  with ContextualDeserializer {

  def createContextual(
    ctxt: DeserializationContext,
    property: BeanProperty): JsonDeserializer[_] = {
    val isNullable = property.getAnnotation(classOf[Nonnull]) == null
    val fieldName = property.getName

    createContextual(isNullable, fieldName)
  }

  protected def createContextual(
    isNullable: Boolean,
    fieldName: String): JsonDeserializer[T] = {
    val constructor = getClass.getConstructor(classOf[Boolean], classOf[String])

    constructor
      .newInstance(java.lang.Boolean.valueOf(isNullable), fieldName)
      .asInstanceOf[JsonDeserializer[T]]
  }

  override def getNullValue(ctxt: DeserializationContext): T = {
    if (!nullable) {
      ExceptionHandler.nullFieldValueFieldErr(fieldName) // handling nullability here
    }
    super.getNullValue(ctxt)
  }
}
```
```scala
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.DeserializationContext

class NonnullIntDeserializer(
  nullable: Boolean = true,
  fieldName: String = null)
  extends NonNullDeserializer[Int](nullable, fieldName) {

  override def deserialize(
    p: JsonParser,
    ctxt: DeserializationContext): Int = {
    super._parseIntPrimitive(p, ctxt)
  }

  override def getNullValue(ctxt: DeserializationContext): Int = {
    super.getNullValue(ctxt)

    0
  }
}
```
then install it 
```scala

import akka.http.scaladsl.model.DateTime
import com.fasterxml.jackson.databind.{ BeanDescription, DeserializationFeature, JsonMappingException, ObjectMapper }
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper
import javax.annotation.Nonnull
import scala.collection.JavaConversions._
import scala.reflect.ClassTag
import scala.util.Try

    val mapper = (new ObjectMapper() with ScalaObjectMapper)
      .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
      .enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS)

    val simpleModule = new SimpleModule()
      .addDeserializer(
        classOf[Int],
        new NonnullIntDeserializer())

```
so, I guess, we can resolve the ticket, which I will do with your permission, @DanielaSfregola
