### ISSUE TITLE
Unable to control logging

### ISSUE THREAD

**Issue by levelonedev** [DanielaSfregola/random-data-generator#31]
Thanks for the awesome project! I understand not wanting to include a logging library in a very small library but I'd appreciate a way to turn off the println's. Do you have any ideas? I'm willing to create the PR myself.

**Comment by DanielaSfregola** [comment]
Hi @levelonedev if you turn off the println you will not be able to see the seed applied to the test session. This implies that you will not been able to make the tests deterministic when needed.

I do not think this is a good idea, what do you think?

**Comment by DanielaSfregola** [comment]
Obviously, I am happy to discuss this further and find a compromise :)

**Comment by levelonedev** [comment]
You bring up a very good point that we would have to roll the dice again to find a failing seed. Scalacheck would print the failing values though and I'd prefer in most cases to add that specific case as a test so that I don't have to wait for arbitrary to find the failing value intermittently in my tests.  

If the pretty print function was override-able it would not be hard to turn it on and off. I wouldn't want to remove it completely and as you brought up I might not since finding a seed that fails again would be pretty hard.

**Comment by DanielaSfregola** [comment]
Cool, I am going to close this ticket.

However, considering the size of the codebase (1 file), if you feel like playing around with logging and propose possible improvements feel free to open a PR!

Cheers,
Daniela
