### ISSUE TITLE
NoSuchElementException: None.get

### ISSUE THREAD

**Issue by pawelkaczor** [DanielaSfregola/random-data-generator#48]
```
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:349)
[info]   at scala.None$.get(Option.scala:347)
[info]   at com.danielasfregola.randomdatagenerator.RandomDataGenerator.random(RandomDataGenerator.scala:17)

```

**Comment by DanielaSfregola** [comment]
Thanks @pawelkaczor for the bug report and fix! I'll see if I can do a quick release for it

**Comment by pawelkaczor** [comment]
I suppose, the reason for the error is that one of my generators uses additional filter: 
```scala
  implicit def anAddParticipant: A[AddParticipant] = Arbitrary { for {
    name <- Gen.oneOf("Paul", "John").suchThat(p => !generatedParticipants.contains(p))
  } yield {
    generatedParticipants = generatedParticipants + name
    AddParticipant(lotteryId, name)
  }} 
```

**Comment by pawelkaczor** [comment]
@DanielaSfregola Thanks. Waiting for the release :-)

**Comment by pawelkaczor** [comment]
Unfortunately this fix does not solve my problem. The exception is gone, but now the test is hanging (I guess because generated value is reused (not regenerated)) :(

**Comment by DanielaSfregola** [comment]
...how do you create `generatedParticipants`?

**Comment by pawelkaczor** [comment]
I need to recall/rethink the test scenario. I will get back to you later.

**Comment by DanielaSfregola** [comment]
Ok, I have reverted the change. 

The general idea is that if your generator needs to be generic enough to provide enough valid results (in particular if you are filtering!). If it is too strict and it cannot find a valid value, then it will not be able to generate a random instance for it failing with a None.get.

I'll close the ticket for now, but please feel free to reopen it if you need help figuring out what's wrong with your generators ;)

**Comment by pawelkaczor** [comment]
Ok. Sorry for the confusion :)

**Comment by pawelkaczor** [comment]
I ended up using scala Tagged Types:

https://github.com/pawelkaczor/akka-ddd/blob/master/akka-ddd-test/src/test/scala/lottery/domain/model/LotterySpecSupport.scala
