### ISSUE TITLE
PrettyPrinterSpec weirdness

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/random-data-generator#52]
...doesn't quite look right! For the following reasons
- it prints to the console (but it shouldn't)
- never fails

....WHAT?!?

Have a look!

**Comment by alexbalonperin** [comment]
Hey, I would be happy to help with this issue but to be honest I am not entirely sure what your code is trying to test.

```
abstract class PrettyPrinterSpecContext extends Scope {
  val printer = {
      val mockPrintF = {_: String => (): Unit}
      spy(new PrettyPrinter(mockPrintF))
  }
}

....

"print an info message" in new PrettyPrinterSpecContext {
    val msg = "This is my info message"
    printer.info(msg)
    there was one(printer).print(s"[info] [RandomDataGenerator] $msg")
}
```

AFAICT, `print` is not a method on your `PrettyPrinter` object. It looks like it comes from `Output` somehow; `there was one(printer)` has all the methods of the `Output` trait. 
https://github.com/etorreborre/specs2/blob/master/common/shared/src/main/scala/org/specs2/io/Output.scala

The implementation of `Output#print` might explain why the tests print to the console.
```
def print(m: Any) = this.printf("%s", m)
```

Maybe you wanted to make sure that `prettyPrint` is only called once? It might be best to collect the log messages into a list and check that the content of the list correspond to what you are expecting.
```
abstract class PrettyPrinterSpecContext extends Scope {
   val logs: ListBuffer[String] = new ListBuffer
   private def append(log: String): Unit = synchronized { logs += log; () }

  val printer = {
      val mockPrintF = (log: String) => append(log)
      spy(new PrettyPrinter(mockPrintF))
  }
}

....

"print an info message" in new PrettyPrinterSpecContext {
    val msg = "This is my info message"
    printer.info(msg)
    logs must haveSize(1)
    logs must_== ListBuffer(s"[info] [RandomDataGenerator] $msg")
}
```

It might not be the best way to do this but it's the simplest version that I could think of. If the above code looks okay I can make a PR. What do you think? 🙂

**Comment by DanielaSfregola** [comment]
Hi @zolrag13,
RandomDataGenerator uses logs to communicate information to the user about the seed used for the test session.

This `PrettyPrinterSpec` test makes sure that the structure of the printed message has always the same structure.

Thanks for your PR, looking at it now

**Comment by DanielaSfregola** [comment]
To be replicated in random-data-generator-magnolia, fixed for random-data-generator

**Comment by DanielaSfregola** [comment]
Replicated in random-data-generator-magnolia in https://github.com/DanielaSfregola/random-data-generator-magnolia/pull/4
