### ISSUE TITLE
Support for Scala.js

### ISSUE THREAD

**Issue by mucahitkantepe** [DanielaSfregola/random-data-generator#57]
I think this library can support Scaka.js because Shapeless supports it.

I am not sure if thats possible but it would be very nice

**Comment by DanielaSfregola** [comment]
Hi @mucahitkantepe,
I think so too! Just not sure where to start, we'll look into it!

In the meanwhile, PRs are always welcome ;)

**Comment by mucahitkantepe** [comment]
Hi @DanielaSfregola, I'm going to start the issue in this week.

**Comment by DanielaSfregola** [comment]
Thanks @mucahitkantepe!

**Comment by mucahitkantepe** [comment]
This doesn't seem easy as I guessed, because current implementation uses scala reflections that scala.js does not have support for it (https://groups.google.com/forum/#!topic/scala-js/xY4Iuq8PVvA).

We need a different approach. I think, things must be done at compile time therefore macros can be used. Since I don't have any experience with scala macros,  I need to do some research about it.
