### ISSUE TITLE
Travis build error for oraclejdk7

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/random-data-generator#71]
Happened with #70:

```
Installing oraclejdk7
$ export JAVA_HOME=~/oraclejdk7
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "BCL"
install-jdk.sh 2018-10-17
Expected feature release number in range of 9 to 12, but got: 7
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "BCL"" failed and exited with 3 during .
```

see https://travis-ci.org/DanielaSfregola/random-data-generator/jobs/468459440

We should investigate why and fix it  -- it seems to happen consistently

**Comment by krishna-meduri** [comment]
@DanielaSfregola Is this because of recent Oracle's move on JDK? (Reference: https://github.com/travis-ci/travis-ci/issues/10290) Assuming you are running the build using Oracle's JDK v7.x. Please let me know your thoughts on this. Thank you.

**Comment by DanielaSfregola** [comment]
Not sure about the reason yet, it could be because of the Oracle's move you mention.
Feel free to give it a try to see if that is the problem (all the travis config are in the repo), PRs are always welcome!

Cheers,
Daniela

**Comment by krishna-meduri** [comment]
Sure. Will try to work on it and will update you. Thank you.

**Comment by DanielaSfregola** [comment]
Fix in commit https://github.com/DanielaSfregola/random-data-generator/pull/73/commits/8e61fce5fd2e09e8f717883672eb6005e2f5592a

It seemed to be just a question of no longer supported jdk in travis
